### ISSUE TITLE
Css Syntax Error

### ISSUE THREAD

**Issue by yohored** [twolfson/gulp.spritesmith#112]
Hi, I have this issue, and no idea what's happening.
If you need further information, please let me know.

![screenshot](https://cloud.githubusercontent.com/assets/3971049/21254234/ee3e0a4c-c39e-11e6-83dc-52251ff9fb5f.jpg)

**Comment by twolfson** [comment]
It looks like you are using SCSS with `postcss` which is designed for CSS. You have 2 options:

- Move to `postcss-scss` and use our sprites mixins in SCSS
- Update your `gulp.spritesmith` configuration to generate CSS instead of SCSS

I'm going to guess you want the latter since you are on `postcss` so here's how you do that:

If files must be named `.scss` in your project, then set `cssFormat`:

```js
spritesmith({
  imgName: 'sprite.png',
  cssName: 'sprite.scss',
  cssFormat: 'css'
})
```

If your files can be named `.css`, then rename the `cssName` and remove a `cssFormat` if there is one:

```js
spritesmith({
  imgName: 'sprite.png',
  cssName: 'sprite.css'
})
```

-------------------

> If you found this help useful and would like to support the project, please consider tipping us here: http://twolfson.com/support-me
