### ISSUE TITLE
Same set of input images but output sprite image is always changing

### ISSUE THREAD

**Issue by foresightyj** [twolfson/gulp.spritesmith#145]
I used cache busting via `gulp-spritesmash` but because `gulp.spritesmith` does not generate the same image, the output file name & content are always changing. This means that each deployment will yield different sprite image and previous cache gets invalidated.

Is there is a way to get deterministic image output?

![image](https://user-images.githubusercontent.com/1296736/62409634-f2bf5900-b60c-11e9-8e53-7e72f3ba1fc9.png)

Above screenshots show the file name is always changing. You can see that those small icons are positioned differently each time.

**Comment by twolfson** [comment]
I'm pretty confident we have sorting mechanisms. Can you try explicitly listing the input images to guarantee they arrive in the desired order?

That being said, this task can can take a while to run. Instead of detecting that the final image has changed, I'd recommend comparing the modified timestamp of the generated spritesheet against the timestamp of the original files (there's probably a `gulp` caching plugin for this)

**Comment by foresightyj** [comment]
Exactly. The input images are fed in different orders occasionally. It is more likely to happen in my office computer (8 out of 10 times) and less likely (only about 1 out of 10) in my home computer, both have a Windows OS. 

This gulp issue  https://github.com/gulpjs/gulp/issues/687 talked about problems caused by `gulp.src` not being able to deliver files in fixed order.

I used `gulp-order` to sort the files right after `gulp.src` and the hash has been consistent ever since.

You mentioned that this plugin has sorting mechanisms so it is insensitive to input file order? But my findings prove that it is actually sensitive.

I didn't quite follow what you mean by `generated spritesheet`. Do you refer to the generated css + image files? They will be generated anew every time.

**Comment by twolfson** [comment]
Great! Glad to hear this is resolved =) Ah, maybe we've disabled the sorting mechanisms over the years due to people wanting custom sorts (e.g. for animations). I don't have a fresh recollection of this entire codebase at the moment =/

With respect to only running the task when a source file has been modified: Yes, by generated spritesheet I mean the generated CSS and image files. The plugin would check the old modified time *before* running the task. A quick search shows something like:

https://www.npmjs.com/package/gulp-diff-build

There should/can also be variations which use the modified timestamp comparison instead of a file hash though

**Comment by foresightyj** [comment]
Thanks for the suggestions. Yes, your suggestion will work too.

I didn't take that approach in the first place though, because I ran `rimraf` over the folder containing `sprite.css` & `sprite-[hash].png` as the first step of gulp. The purpurse is to avoid more and more `sprite-[hash].png` appearing in that folder.

Since my problem has been answered, I am going to close this issue. Thanks for the help!
