### ISSUE TITLE
Unable to commit node_modules

### ISSUE THREAD

**Issue by chbloemer** [twolfson/gulp.spritesmith#34]
The node_modules folder can't be commited git because gulp.spritesmith has a dependency to url 0.7.9.

I get the following error:
> fatal: Not a git repository: /Users/Mathias/Projects/punycode.js/.git/modules/vendor/docdown

This module had the same issue:
https://github.com/webpack/node-libs-browser/issues/9

**Comment by twolfson** [comment]
It looks like `url2` switched from a semver that would pick up `0.10.x` between `1.0.2` and `1.0.3`.

https://github.com/kriskowal/url2/blob/v1.0.2/package.json#L20

https://github.com/kriskowal/url2/blob/v1.0.3/package.json#L20

The `master` branch has a better semver for `0.10.x` itself but hasn't been published to `npm`. I am going to see if we can get a release rather than moving back to an older version.

**Comment by leevigraham** [comment]
Watching this…

**Comment by twolfson** [comment]
I have bumped the issue on the dependency's repo. It made progress but stopped

**Comment by twolfson** [comment]
This has been fixed up in `3.5.3`. Thanks for the bug report!
