### ISSUE TITLE
SCSS output issue

### ISSUE THREAD

**Issue by web2style** [twolfson/gulp.spritesmith#43]
If I add an image with two dashes in its name like `image--success.png`, `$image-success` (note one dash instead of two) variable is created with `cssFormat: 'scss'` option enabled, while everything works correctly with LESS: `@image--success`.

**Comment by twolfson** [comment]
Hm, that is strange. I will take a look by the end of next weekend.

**Comment by twolfson** [comment]
I have reproduced the issue in:

**Comment by twolfson** [comment]
I have reproduced the issue in:

https://gist.github.com/twolfson/ad25280947c96f9c7d73

The source of the problem is that we introduced variable normalization in `2.6.0`:

https://github.com/twolfson/gulp.spritesmith/blob/3.5.4/CHANGELOG.md

We introduced this normalization to normalize images that had invalid casing for their CSS equivalent (e.g. `dashes` aren't universally accepted).

The variables still should have the proper `--` in the generated CSS rules. However, to remove this normalization, we can pass in an empty translation array via `cssOpts.variableNameTransforms`:

```js
gulpSpritesmith({
  cssName: 'sprites.sass',
  imgName: 'spritesheet.png',

  cssOpts: {
    variableNameTransforms: []
  }
})
```

More information on transformations can be found here:

https://github.com/twolfson/spritesheet-templates/tree/9.4.1#less
