### ISSUE TITLE
Tried to upgrade and got dependency error

### ISSUE THREAD

**Issue by CoralSilver** [twolfson/gulp.spritesmith#84]
NPM error:  deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

**Comment by twolfson** [comment]
Strange, that should be a warning not an error since it's a deprecation. The underlying issue is `save-pixels` in `pixelsmith` using an out of date version (determined via `npm ls`).

There's an open issue here: https://github.com/scijs/save-pixels/issues/17

Would you be interested in submitting a PR to patch it on their repo? They are usually pretty responsive

**Comment by CoralSilver** [comment]
Sure thanks.

**Comment by twolfson** [comment]
@CoralSilver I'm confused why you never submitted a PR to patch the repo despite saying you were going to =/

It looks like Mikola finally patched it recently in a patch release so this issue should be resolved now.
