### ISSUE TITLE
Gulp spritesmith 'getting started' task is doing nothing

### ISSUE THREAD

**Issue by RohitRane** [twolfson/gulp.spritesmith#87]
0
down vote
favorite
I just copy pasted the getting started task :

```
var gulp = require('gulp');
var spritesmith = require('gulp.spritesmith');

gulp.task('sprite', function () {
    console.log("inside sprite");
    var spriteData = gulp.src('/assets/images/*.jpg').pipe(spritesmith({
        imgName: 'sprite.png',
        cssName: 'sprite.css'
    }));

    return spriteData.pipe(gulp.dest('/assets/images/sprites'));
});
```
When I run this task I get the response :
```
[19:42:03] Using gulpfile D:\Phase Zero\AfterMarket\Application\gulpfile.js
[19:42:03] Starting 'sprite'...
inside sprite
[19:42:03] Finished 'sprite' after 18 ms
```
 
But if I go to '/assets/images/sprites'  its empty !

How do I debug here?

**Comment by twolfson** [comment]
An empty set of results with no error message means that no files were found via `gulp.src`. In your case, it's due to using `/assets` which means look at the root directory assets on your file system (which prob doesn't exist). Try adjusting it to `gulp.src('assets/images/*.jpg')`.

If you want to debug further, then the input files can be logged via `gulp-debug`:

https://www.npmjs.com/package/gulp-debug
